require("tl").loader()

local FormatterOptions = require("formatter.options")
local assert = require("luassert")

describe("FormatterOptions.from_args", function()

    describe("defaults", function()
        it("returns default options when only files are given", function()
            local opts, err = FormatterOptions.from_args({"file.tl"})
            assert.is_nil(err)
            assert.is_false(opts.check_only)
            assert.same("nothing", opts.log_level)
            assert.same(4, opts.indent_width)
            assert.same(88, opts.max_line_width)
            assert.is_true(opts.sort_requires)
            assert.same({"file.tl"}, opts.files)
        end)
    end)

    describe("files", function()
        it("collects a single positional argument as a file", function()
            local opts, err = FormatterOptions.from_args({"a.tl"})
            assert.is_nil(err)
            assert.same({"a.tl"}, opts.files)
        end)

        it("collects multiple positional arguments as files", function()
            local opts, err = FormatterOptions.from_args({"a.tl", "b.tl", "c.tl"})
            assert.is_nil(err)
            assert.same({"a.tl", "b.tl", "c.tl"}, opts.files)
        end)

        it("collects files interspersed with flags", function()
            local opts, err = FormatterOptions.from_args({"a.tl", "--check", "b.tl"})
            assert.is_nil(err)
            assert.same({"a.tl", "b.tl"}, opts.files)
            assert.is_true(opts.check_only)
        end)

        it("returns an error when no files are given", function()
            local opts, err = FormatterOptions.from_args({"--check"})
            assert.is_nil(opts)
            assert.is_not_nil(err)
        end)

        it("returns an error when args is empty", function()
            local opts, err = FormatterOptions.from_args({})
            assert.is_nil(opts)
            assert.is_not_nil(err)
        end)
    end)

    describe("--check", function()
        it("sets check_only to true", function()
            local opts, err = FormatterOptions.from_args({"--check", "file.tl"})
            assert.is_nil(err)
            assert.is_true(opts.check_only)
        end)

        it("check_only is false without the flag", function()
            local opts, err = FormatterOptions.from_args({"file.tl"})
            assert.is_nil(err)
            assert.is_false(opts.check_only)
        end)
    end)

    describe("--no-sort-requires", function()
        it("sets sort_requires to false", function()
            local opts, err = FormatterOptions.from_args({"--no-sort-requires", "file.tl"})
            assert.is_nil(err)
            assert.is_false(opts.sort_requires)
        end)

        it("sort_requires is true without the flag", function()
            local opts, err = FormatterOptions.from_args({"file.tl"})
            assert.is_nil(err)
            assert.is_true(opts.sort_requires)
        end)
    end)

    describe("--log-level", function()
        it("sets log_level to the given value", function()
            local opts, err = FormatterOptions.from_args({"--log-level", "info", "file.tl"})
            assert.is_nil(err)
            assert.same("info", opts.log_level)
        end)

        it("accepts debug", function()
            local opts, err = FormatterOptions.from_args({"--log-level", "debug", "file.tl"})
            assert.is_nil(err)
            assert.same("debug", opts.log_level)
        end)

        it("returns an error when no argument follows", function()
            local opts, err = FormatterOptions.from_args({"--log-level"})
            assert.is_nil(opts)
            assert.is_not_nil(err)
        end)
    end)

    describe("--indent", function()
        it("sets indent_width to the given value", function()
            local opts, err = FormatterOptions.from_args({"--indent", "2", "file.tl"})
            assert.is_nil(err)
            assert.same(2, opts.indent_width)
        end)

        it("returns an error when no argument follows", function()
            local opts, err = FormatterOptions.from_args({"--indent"})
            assert.is_nil(opts)
            assert.is_not_nil(err)
        end)

        it("returns an error for a non-integer value", function()
            local opts, err = FormatterOptions.from_args({"--indent", "two", "file.tl"})
            assert.is_nil(opts)
            assert.is_not_nil(err)
        end)

        it("returns an error for zero", function()
            local opts, err = FormatterOptions.from_args({"--indent", "0", "file.tl"})
            assert.is_nil(opts)
            assert.is_not_nil(err)
        end)

        it("returns an error for a negative value", function()
            local opts, err = FormatterOptions.from_args({"--indent", "-1", "file.tl"})
            assert.is_nil(opts)
            assert.is_not_nil(err)
        end)
    end)

    describe("--line-length", function()
        it("sets max_line_width to the given value", function()
            local opts, err = FormatterOptions.from_args({"--line-length", "100", "file.tl"})
            assert.is_nil(err)
            assert.same(100, opts.max_line_width)
        end)

        it("returns an error when no argument follows", function()
            local opts, err = FormatterOptions.from_args({"--line-length"})
            assert.is_nil(opts)
            assert.is_not_nil(err)
        end)

        it("returns an error for a non-integer value", function()
            local opts, err = FormatterOptions.from_args({"--line-length", "wide", "file.tl"})
            assert.is_nil(opts)
            assert.is_not_nil(err)
        end)

        it("returns an error for zero", function()
            local opts, err = FormatterOptions.from_args({"--line-length", "0", "file.tl"})
            assert.is_nil(opts)
            assert.is_not_nil(err)
        end)
    end)

    describe("unknown flags", function()
        it("returns an error for an unrecognised flag", function()
            local opts, err = FormatterOptions.from_args({"--unknown", "file.tl"})
            assert.is_nil(opts)
            assert.is_not_nil(err)
        end)

        it("error message names the bad flag", function()
            local opts, err = FormatterOptions.from_args({"--bad-flag", "file.tl"})
            assert.is_nil(opts)
            assert.truthy(err:find("--bad-flag", 1, true))
        end)
    end)

    describe("combined flags", function()
        it("parses all flags together", function()
            local opts, err = FormatterOptions.from_args({
                "--check",
                "--no-sort-requires",
                "--log-level", "debug",
                "--indent", "2",
                "--line-length", "120",
                "a.tl",
                "b.tl",
            })
            assert.is_nil(err)
            assert.is_true(opts.check_only)
            assert.is_false(opts.sort_requires)
            assert.same("debug", opts.log_level)
            assert.same(2, opts.indent_width)
            assert.same(120, opts.max_line_width)
            assert.same({"a.tl", "b.tl"}, opts.files)
        end)
    end)
end)
