-- Fuzz driver for the formatter. Run from repo root:
--   lua fuzz/fuzz.lua fuzz/corpus/*.tl
-- On failures, writes spec/formatter/fuzz_regressions_spec.lua for debugging.
require("tl").loader()

local rewriter = require("formatter.rewriter")
local FormatterOptions = require("formatter.options")

local function read_file(path)
    local f = io.open(path, "r")
    if not f then return nil end
    local content = f:read("*a")
    f:close()
    return content
end

-- Finds the minimum = level so the content can be embedded in a Lua long string.
local function long_string_embed(s)
    local max_level = -1
    for closing in s:gmatch("]=*]") do
        local level = #closing - 2
        if level > max_level then max_level = level end
    end
    local eq = string.rep("=", max_level + 1)
    return "[" .. eq .. "[" .. s .. "]" .. eq .. "]"
end

local failures = {}
local total = 0

for i = 1, #arg do
    local path = arg[i]
    total = total + 1
    local content = read_file(path)

    if not content then
        io.stderr:write("ERROR: could not read " .. path .. "\n")
        table.insert(failures, { kind = "crash", path = path, content = "", error = "could not read file" })
    else
        local ok, result = pcall(rewriter.rewrite, content, path, FormatterOptions.default())
        if not ok then
            io.stderr:write("CRASH: " .. path .. "\n" .. tostring(result) .. "\n")
            table.insert(failures, { kind = "crash", path = path, content = content, error = tostring(result) })
        elseif #result.parse_errors == 0 then
            local ok2, result2 = pcall(rewriter.rewrite, result.output, path, FormatterOptions.default())
            if not ok2 then
                io.stderr:write("CRASH on second pass: " .. path .. "\n" .. tostring(result2) .. "\n")
                table.insert(failures, { kind = "crash", path = path, content = result.output, error = "second pass: " .. tostring(result2) })
            elseif result2.changed then
                io.stderr:write("NOT_IDEMPOTENT: " .. path .. "\n")
                table.insert(failures, { kind = "not_idempotent", path = path, content = result.output })
            end
        end
    end
end

io.stdout:write("Failures: " .. tostring(#failures) .. " / " .. tostring(total) .. "\n")

if #failures > 0 then
    local spec_path = "fuzz/regressions_spec.lua"
    local f = assert(io.open(spec_path, "w"))

    f:write("-- Generated by fuzz/fuzz.lua. Do not commit.\n")
    f:write("-- Run: busted fuzz/regressions_spec.lua\n\n")
    f:write('require("tl").loader()\n')
    f:write('local rewriter = require("formatter.rewriter")\n')
    f:write('local FormatterOptions = require("formatter.options")\n')
    f:write('local helpers = require("spec.formatter.helpers")\n\n')
    f:write('describe("fuzz regressions", function()\n\n')

    for _, failure in ipairs(failures) do
        local name = failure.path:match("([^/]+%.tl)$") or failure.path
        local embedded = long_string_embed(failure.content)

        if failure.kind == "crash" then
            f:write("    -- " .. failure.error:gsub("\n", "\n    -- ") .. "\n")
            f:write('    it("does not crash: ' .. name .. '", function()\n')
            f:write("        rewriter.rewrite(" .. embedded .. ', "test.tl", FormatterOptions.default())\n')
            f:write("    end)\n\n")
        elseif failure.kind == "not_idempotent" then
            f:write('    it("is idempotent: ' .. name .. '", function()\n')
            f:write("        helpers.check(" .. embedded .. ")()\n")
            f:write("    end)\n\n")
        end
    end

    f:write("end)\n")
    f:close()

    io.stdout:write("Regression spec: busted " .. spec_path .. "\n")
end

os.exit(#failures == 0 and 0 or 1)
